branches:
  except:
    - gh-pages

skip_tags: true

skip_commits:
  message: \[(ci skip|skip ci)\].*

clone_depth: 50

cache:
  - packages
  - node_modules

install:
  - ps: Install-Product node ''
  - npm install
  - choco install calibre
  - cmd: set PATH=%PATH%;C:\Program Files\Calibre2\

build_script:
  - cmd: build.cmd GenerateAll

environment:
  access_token:
    secure: /RXusYkOTtsXn3OKWHg65Tbj8rasEzKbyMS+qGqCjqdk+Hcsu1CKYcUJ0hvd1Shd

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.name "pocketberserker"
  - git config --global user.email "pocketberserker@gmail.com"
  - git config --global push.default simple
  - cmd: ./build.cmd ReleaseFromAppVeyor

artifacts:
  - path: gitbook\book.pdf
  - path: gitbook\book.epub

